services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    #no codigo foi criado as variaveis como se a aplicação tivesse um banco a api não precisa...
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=banco-teste
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: banco-teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: #por padrão o compose cria uma rede padrão  mas foi especificado uma rede
      - app-network

volumes:
  pgdata:

networks:
  app-network:
