stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE ./app
  only:
    - main

test:
  stage: test
  script:
    - docker run -d --name app -p 5000:5000 $DOCKER_IMAGE
    - sleep 10 # Aguarda a api iniciar
    - curl -f http://localhost:5000 #teste da api
  only:
    - main